nav:
  Home: /
  About: /about/
  Writing: /archives/
  Projects: http://github.com/tzvetkov75

projects_url: http://github.com/tzvetkov75

customize:
    gravatar:
        email: 
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/tzvetkov75/solar-theme-hexo
        twitter: /
        facebook: /
        linkedin: /
    post_count: 5
    highlight: railscasts
    banner_image:  /images/bg_cactus.jpg

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
