nav:
  Home: /home/
  About: /about/
  Writing: /archives/
  Projects: http://github.com/tzvetkov75

projects_url: http://github.com/tzvetkov75

customize:
    gravatar:
        email: 
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/tzvetkov75/solar-theme-hexo
        twitter: /
        facebook: /
        linkedin: /
    post_count: 5
    highlight: lightcode

# keept it like this to add the root path (probably a bug)
root: ..

solar:
    # factor between 0 (fast), 1(normal), 2(very slow)  
    speed: 1
    sun_image: /images/sun.png
    earth_image: /images/earth.png
    jupiter_image: /images/jupiter.png
    mars_image: /images/mars.png
    mercury_image: /images/mercury.png
    shadow_image: /images/shadow.png
    venus_image: /images/venus.png

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
